# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('profile_pic', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=300)),
            ],
        ),
    ]
