# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_name',
            field=models.CharField(default='default name', max_length=30),
            preserve_default=False,
        ),
    ]
