# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_follower', to='microblog.User')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_creator', to='microblog.User')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(max_length=10),
        ),
    ]
