# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0008_auto_20161002_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(default='pub', max_length=10),
        ),
        migrations.AddField(
            model_name='saves',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microblog.Post'),
        ),
        migrations.AddField(
            model_name='saves',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microblog.User'),
        ),
        migrations.AlterUniqueTogether(
            name='saves',
            unique_together=set([('user', 'post')]),
        ),
    ]
