# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0009_auto_20161003_2041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saves',
            unique_together=set([]),
        ),
    ]
