# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0010_auto_20161003_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
