# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 08:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microblog', '0011_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
